### ISSUE TITLE
24w33a MC java snapshot TODO list.

### ISSUE THREAD

**Issue by DragonWrangler1** [VoxelForge/VoxelForge#124]
# **Minecraft Snapshot 24w33a released on Aug 15, 2024**

# _Experimental features_

## Bundles

- [x] A Bundle only fits one stack (usually 64 items) but it can be a mixture of many different item types
- [x] You can insert items into a Bundle directly in the inventory
- Bundles have a tooltip that shows the items inside. (Not possible with the engine)
- If a Bundle has less than 8 item types inside, the tooltip will show all of them. Otherwise the tooltip will show the top two rows of items and the others will be hidden below.
- [x] You can select any of the visible items to pull out of the Bundle.
- [x] Right-click to take the first item
- Use the number keys or scroll wheel to select a different item, then right-click to take it
- [x] When selecting an item to remove, the Bundle icon shows that item poking out of the Bundle
- [x] When holding a Bundle in hand, you can empty it onto the ground by right-clicking
- [x] The Bundle is crafted with one String above one Leather

### The controls have changed from the original prototype:
- [x] Use left-click to put an item into a Bundle
- [x] Use right-click to remove the top item type from a Bundle
- When the Bundle tooltip is visible, use number keys or the mouse wheel to select a different item type then use right-click to remove it. Not possible with the engine.

### Redstone Wire
- [ ] The performance impact of Redstone wire (connected blocks of Redstone Dust) has been improved
- [ ] Redstone wire now only triggers block updates on blocks that may receive power from the wire
- [ ] Before a line of wire causes block updates, the new signal strength of all connected wires is set
- [ ] The update order around Redstone wire has been changed
- [ ] The aim is to make wire work the same, independent of position and orientation
- [ ] When possible the order is deterministic based on the context the updates are caused in
 - [ ] When there is not enough context to fully determine the order, the rest is picked at random

### Order in Which a Line of Wire Changes
- [ ] When a line of wire turns on, the wires closer to the power source will cause block updates first
- [ ] When a line of wire turns off, the wires closer to where the power source was, will cause block updates first
- [ ] When two wires have the same distance to the power source, which of them causes updates first is picked at random
- [ ] The random choice is made once for the entire line of wire, to limit the amount of possible outcomes
- [ ] This means, when powering a line of wire from the side, it randomly chooses one of two possible update orders
- [ ] The advantage of having few possible update orders is that the results are more predictable

### Block Updates Around a Wire
- [ ] The order in which blocks around the wire update is based on the direction the wire received an update from
- [ ] Currently, the order is: back, front, left, right, down, up
- [ ] left and right may be swapped, depending on the random choice made by the line of wire
- [ ] When the updates are further distributed through solid blocks, the same order is applied there

### Movement Changes
- [ ] Minecarts will articulate their movement better when going fast, riding on the rail all the time
- [ ] Minecarts will now smoothly turn along with the track and are less likely to halt or derail
- [ ] Minecarts can now jump better
- [ ] They keep their vertical momentum when the track ends with a slope
- [ ] Minecarts will tilt to visually articulate while in the air
- [ ] No rail grinding sound is played when Minecarts are flying through the air
- [ ] Added a new accessibility setting that makes players follow the rotation of Minecarts they ride
Defaults to off
- [ ] Add new gamerule minecartMaxSpeed that changes the maximum speed of Minecarts
Defaults to 8 and goes up to 1000 blocks per second.

### Minecart Changes
- [x] Minecarts can no longer be placed within another Minecart by the player or a dispenser
- [ ] Minecarts can now consistently be placed next to each other along a track
- [ ] Minecarts now pick up mobs more consistently when moving along a track

## Misc other changes
- [ ] dolphins, and squid have baby variants.
- [ ] trial chambers additions (various)
- [ ] new banner patterns
- - [ ] updated rarity for certain items
- [x] various bug fixes
