### ISSUE TITLE
24w34a MC java snapshot TODO list

### ISSUE THREAD

**Issue by DragonWrangler1** [VoxelForge/VoxelForge#131]
# **Minecraft Snapshot 24w34a released on Aug 21, 2024**

# _Experimental features_

## Bundles
- The Bundle tooltip now fits 3 rows and can always show at least 8 item types

## Redstone Experiments
- [ ] Redstone wire updates now have a left-first preference

## Minecart Improvements

- [ ] Minecarts no longer forcefully snap to the center of a block when landing on a rail
- [ ] Minecarts snap to corners along the diagonal, and snaps after being pushed by a Piston
- [ ] This allows for Piston bolts and similar contraptions
- [ ] Dispensers are allowed to stack Minecarts again
- [ ] Minecarts now more easily come to rest at opposing slopes
- [ ] Minecarts no longer tilt during a short fall, or when they are falling straight down
- [ ] Minecarts are now placed (or dispensed) with the correct rotation straight away when put on rails
- [ ] They are also placed with the correct rotation onto slopes
- [ ] Minecarts no longer phase through blocks on slopes when going up or down, they collide instead

## Misc other changes
- [ ] various bug fixes
