### ISSUE TITLE
Roadmap June 2024

### ISSUE THREAD

**Issue by DragonWrangler1** [VoxelForge/VoxelForge#2]
All things for the roadmap of June 2024.

-  [ ]  1. Cleanup code. Simplify where possible and use JSON
-  [ ]  2. Fix as many bugs as possible
-  [ ] 3. Dev versions are very random.  Start making each version have a goal. (probably gonna move this one to july or august roadmap
