### ISSUE TITLE
Remake a few things to be more minecraft like.

### ISSUE THREAD

**Issue by DragonWrangler1** [VoxelForge/VoxelForge#24]
- [x] Hide default text on the screen, and replace it with text at the bottom.
- [x] remake the chat hud so it's at the bottom.
- [x] make the default font a more minecraft like font.
- [x] get or make a new font so that it isn't under the CC-BY-ND license.
