### ISSUE TITLE
Poisonous potato checklist

### ISSUE THREAD

**Issue by DragonWrangler1** [VoxelForge/VoxelForge#265]
a TODO list for all things potato.

**Blocks**
- [x] Pedestal.
- [x] Potato Portal.
- [x] Big Brain.
- [x] Potato battery.
- [x] poisonous potato cutter.
- [x] Frying table.
- [x] Potato refinery.
- [x] Flotato.
- [ ] Flotater. (Can't be done without large performance drops.)
- [x] Powerful potato.
- [x] Strong roots.
- [x] Weak roots.
- [x] Block of Amber.
- [x] Potato flower.
- [x] Potato bud.
- [x] Potato stem.
- [x] Potato planks.
- [x] Potato leaves.
- [ ] Potato fruit.
- [ ] Potato pedicule.
- [ ] Potato Sprouts.
- [ ] Terre de Pomme.
- [ ] Peelgrass block.
- [ ] Corrupted Peelgrass block.
- [ ] Poison farmland.
- [ ] Poison Path.
- [ ] Gravtater.
- [ ] Vicious Potato.
- [ ] Poisonous Potato Ore.
- [ ] Deepslate Poisonous Potato Ore.
- [ ] Resin Ore.
- [ ] Potone.
- [ ] Taterstone.
- [ ] Poisonous Potato Bricks.
- [ ] Expired Poisonous Potato Bricks.
- [ ] Charred Poisonous Potato Bricks.
- [ ] Poisonous Mashed Potatoes.
- [ ] Poisonous Potato Block.
- [ ] Poisonous potato headpiece.
- [ ] Poisonous potato head block.
- [ ] Block of potato peels.
- [ ] Block of corrupted potato peels.

**Items**

- [ ] Poisonous Potato Plant.
- [ ] Poisonous Potato Fries.
- [ ] Poisonous Potato Slices.
- [ ] Poisonous Potato Sticks.
- [ ] Poisonous Potato Chips.
- [ ] Hash Browns.
- [ ] Potato eye.
- [ ] Potatiesh, Greatstaff of the Peasant.
- [ ] Potato of Knowledge.
- [ ] Venomous Potato.
- [ ] Hot Potato.
- [ ] Golden Poisonous Potato.
- [ ] Enchanted Golden Poisonous Potato.
- [ ] Poisonous Potato Hammer.
- [ ] Poisonous Pota-toes.
- [ ] Poisonous Potato Chestplate.
- [ ] Poisonous Polytra.
- [ ] Potato Oil.
- [ ] Poisonous Potato Oil.
- [ ] Toxic Beam.
- [ ] Lashing Potato.
- [ ] Potato Peeler.
- [ ] Toxic resin.
- [ ] Amber Gem.
- [ ] Potato Peels.
- [ ] Corrupted Potato Peels.

**Mobs**

- [ ] Batato.
- [ ] Poisonous Potato Zombie.
- [ ] Toxifin Slab.
- [ ] PlagueWhale slab.
- [ ] Mega Spud.

**Mob Textures**

- [ ] Various.

**Structures**

- [ ] Colosseum.
- [ ] potato mineshaft.
- [ ] Ruined portatol
- [ ] Potato Village.

**Features**

- [ ] Potato Tree.
- [ ] Hash Well.
- [ ] Potato Geode.

**Paintings**

- [ ] Various

**Dimensions**

- [ ] Poisonous Potato Dimension.

**Biomes**

- [ ]

**Comment by DragonWrangler1** [comment]
Gonna be moved to an outside mod.
